---
title: "Inhaltsverzeichnis"
output: html_document
---

***

- 1 Theoretische Einführung (30min)

    - 1.1 Warum R? Motivation (DS) (5min)
        - Archäologische Daten
          - Datentypen
          - Skalenniveaus
        - Fragestellungen
        - Reproduzierbarkeit
        - Vor- und Nachteile von R

    - 1.2 R als Programmiersprache (CS) (5min)
        - Geschichte
        - R Funktionsprinzip
        - Libraries
        - Hilfefunktionen

    - 1.3 Einfach Objekte (CS) (15min)
        - Überblick Objekte
            - Welche Objekte gibt es?
            - Welche Objekte wofür?
        - Einfache Objekte anlegen
            - Constants
            - Vectors
            - data.frames
        - Einfache Objekte adressieren
        - *Übung*
    
    - 1.4 Einfache Funktionen (DS) (5min)
        - Überblick Funktionen
            - Aufbau und Zweck einer Funktion
            - Eingabewerte und Rückgabewerte
        - Funktionen anlegen

***

- 2 Datenverstehen und beschreiben mit R (1h)

    - 2.1 Datenhaltung (DS) (5min)

    - 2.2 Daten laden und speichern (DS) (5min)
        - Daten aus Dateien laden -> *Übung*
        - (Daten aus Datenbanken und dem Internet laden)

    - 2.3 Daten verarbeiten und vorbereiten (40min)
        - Tidy-Data-Prinzip (CS) 
        - Daten reinigen und aufbereiten (CS) 
            - merging (%in%) -> *Übung*
            - factors -> *Übung*
            - Duplikate entfernen 
            - Sortierung (sort, order) -> *Übung*
            - grouping/aggregation -> *Übung*
            - Pivotieren (tapply) (DS) -> *Übung*
            - Wide to Long und Long to Wide -> *Übung*
            - Subsetting (subset, filter) -> *Übung*

    - 2.4 Deskriptive Statistik (DS) (10min)
      - Standartfunktionen (min, max, mean, stdabw, ...) -> *Übung*

***

- 3 Daten visualisieren (1h)

    - 3.1 ggplot2 - Theorie (CS) (10min)
        - Geschichte und Hintergrund
        - Abgrenzung zu plot()
        - Struktur und Syntax
    
    - 3.2 ggplot2 - Praxis (DS)
        - 3.2.1 **Anwendung 1: Histogramm** (15min) -> *Übung*
        - 3.2.2 **Anwendung 2: Scatterplot** (15min) -> *Übung*
        - 3.2.2 **Anwendung 3: Barplot** (15min) -> *Übung*
        - 3.2.3 Anwendung 4: Boxplot (Bonus)
        - 3.2.4 Erweiterungen (Bonus)
          - Densitykurven
          - Regressionskurven
        - 3.2.5 Anwendung 5: Kartierung (CS) (Bonus)

***
